name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 8
          run_install: true
      - name: Lint
        run: |
          pnpm run lint
      - name: Test
        env:
          CI: true
          COVERALLS_GIT_BRANCH: ${{ github.ref }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          pnpm run test --coverage
          pnpm run coveralls
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: snapshot-diff
          path: tests/__image_snapshots__/__diff_output__
      - name: Build
        run: |
          pnpm run build
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm run release
